/// Flutter icons StormWatchIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  StormWatchIcons
///      fonts:
///       - asset: fonts/StormWatchIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class StormWatchIcons {
  StormWatchIcons._();

  static const _kFontFam = 'StormWatchIcons';

  static const IconData bridge_four =
      const IconData(0xe800, fontFamily: _kFontFam);
}
